Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
  
Metrics/AbcSize:
  Enabled: false
  
Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/NumericLiteralPrefix:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false
